# Generated by Django 2.2.12 on 2021-01-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0019_gallery_g_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='innovation_catgry',
            field=models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (2, 'electronics'), (3, 'vr'), (4, 'science'), (5, 'startups'), (6, 'None')], default=4),
        ),
    ]
