# Generated by Django 2.2.12 on 2020-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_post_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20),
        ),
    ]
