# Generated by Django 2.2.12 on 2021-01-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0020_auto_20210105_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alt_text',
            field=models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery'), ('Events', 'Events')], default='Events', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery'), ('Events', 'Events')], default='Innovations', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_text',
            field=models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery'), ('Events', 'Events')], default='Innovations', max_length=20),
        ),
    ]
