# Generated by Django 2.2.12 on 2021-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0025_auto_20210307_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_dec',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
