# Generated by Django 2.2.12 on 2020-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dimage',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
