# Generated by Django 2.2.12 on 2021-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0016_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='g_thumb',
            field=models.ImageField(blank=True, upload_to='images/thumb/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='g_video',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
