# Generated by Django 2.2.12 on 2021-02-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0022_event_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_author',
            field=models.CharField(default='Reporter', max_length=20),
        ),
    ]
