# Generated by Django 2.2.12 on 2021-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0024_auto_20210307_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dimage5',
        ),
        migrations.AlterField(
            model_name='post',
            name='dimage2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dimage3',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dimage4',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/4'),
        ),
    ]
