# Generated by Django 2.2.12 on 2020-12-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_post_dimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='inncat',
        ),
        migrations.AddField(
            model_name='post',
            name='innovation_catgry',
            field=models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (0, 'electronics'), (2, 'vr'), (3, 'science'), (4, 'None')], default=4),
        ),
    ]
