# Generated by Django 2.2.12 on 2021-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0023_event_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
    ]
