# Generated by Django 2.2.12 on 2021-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0025_auto_20210219_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
    ]
