# Generated by Django 2.2.12 on 2021-02-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0026_auto_20210219_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media_status',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image'), ('link', 'link')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='innovation_catgry',
            field=models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (2, 'electronics'), (3, 'vr'), (4, 'science'), (5, 'startups'), (6, 'None')], default=6),
        ),
    ]
