# Generated by Django 2.2.12 on 2020-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_auto_20201225_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20),
        ),
    ]
