# Generated by Django 2.2.12 on 2021-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0018_remove_gallery_g_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='g_thumb',
            field=models.ImageField(blank=True, upload_to='images/thumb/%Y/%m/%d/'),
        ),
    ]
