# Generated by Django 2.2.12 on 2020-12-29 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0010_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='g_thumb',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/thumb/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='media_status',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image')], default='video', max_length=20),
        ),
    ]
