# Generated by Django 2.2.12 on 2021-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0028_auto_20210321_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dimage',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
