# Generated by Django 2.2.12 on 2020-12-31 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0013_up_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_images',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='up_images',
            name='image',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
