# Generated by Django 2.2.12 on 2020-12-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_auto_20201225_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dimage',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='innovation_catgry',
            field=models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (2, 'electronics'), (3, 'vr'), (4, 'science'), (5, 'None')], default=4),
        ),
    ]
