# Generated by Django 2.2.12 on 2021-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0017_auto_20210102_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='g_thumb',
        ),
    ]
