# Generated by Django 2.2.12 on 2020-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_auto_20201227_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('innovation_catgry', models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (2, 'electronics'), (3, 'vr'), (4, 'science'), (5, 'None')], default=4)),
                ('alt_text', models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20)),
                ('section', models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20)),
            ],
        ),
    ]
