# Generated by Django 2.2.12 on 2020-12-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_gall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('alt_text', models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20)),
                ('g_image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('g_video', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('g_content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Gall',
        ),
    ]
