# Generated by Django 2.2.12 on 2020-12-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0011_auto_20201229_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('alt_text', models.CharField(choices=[('Innovations', 'Innovations'), ('Articles', 'Articles'), ('Reviews', 'Reviews'), ('Gallery', 'Gallery')], default='Innovations', max_length=20)),
                ('e_thumb', models.ImageField(upload_to='images/thumb/%Y/%m/%d/')),
                ('e_description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
