# Generated by Django 2.2.12 on 2021-03-07 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0023_event_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='dimage2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dimage3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dimage4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dimage5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_author',
            field=models.CharField(default='REPORTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media_status',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image'), ('link', 'link')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='innovation_catgry',
            field=models.IntegerField(choices=[(0, 'AI'), (1, 'robotics'), (2, 'electronics'), (3, 'vr'), (4, 'science'), (5, 'startups'), (6, 'None')], default=6),
        ),
    ]
