# Generated by Django 2.2.12 on 2021-03-21 08:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0026_post_meta_dec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dimage',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1024, 768], upload_to='images/%Y/%m/%d/'),
        ),
    ]
